<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Zishan90</name>
   <tag></tag>
   <elementGuidId>dd919ec6-7ba1-4b28-ae57-d9cff9f9e9ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#userName-value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='userName-value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>129ef9c1-3337-4103-b577-0a2f3743e743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-label</value>
      <webElementGuid>fcfb0c3b-64a7-469a-a679-4b98d473b94c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#000000</value>
      <webElementGuid>9ab650b7-e4c6-4fd2-b18a-98b82088acc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userName-value</value>
      <webElementGuid>53a23385-65cf-4502-a48e-eeaf4999b236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Zishan90</value>
      <webElementGuid>0fb6ca1c-607d-4777-ae30-f2ca114e360c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-wrapper&quot;)/div[@class=&quot;text-right col-md-4 col-sm-12&quot;]/label[@id=&quot;userName-value&quot;]</value>
      <webElementGuid>a86a7dfa-8b0c-47dc-a7c5-2ad01cc8cb33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='userName-value']</value>
      <webElementGuid>6cdc763a-f42a-4dea-800d-a8b887bc78c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-wrapper']/div/label[2]</value>
      <webElementGuid>7b8196eb-4cd5-462f-9910-6b1be42d6ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]</value>
      <webElementGuid>c2f195c1-99ae-4335-b998-6ecb0f63409a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'userName-value' and (text() = 'Zishan90' or . = 'Zishan90')]</value>
      <webElementGuid>0451020d-369d-4a17-a2f0-5294aa4af3ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
