<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>ce3d6bd1-bf1c-4e30-988b-5ac3b3626687</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#closeSmallModal-ok</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='closeSmallModal-ok']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>65ec58d9-e49e-4839-95dc-5e9bba27363b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>closeSmallModal-ok</value>
      <webElementGuid>69c03ea3-500a-440a-ba8b-4cbd85501670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0c3acd98-3d98-4268-9ba9-a4f0adefe4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>24c66309-fb7f-4129-8ef1-816ce8da2aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>daae14b0-12b7-4b70-9124-1e5a126a2f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;closeSmallModal-ok&quot;)</value>
      <webElementGuid>bd6b80ce-ce3f-4bca-addc-a5159d60e5e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='closeSmallModal-ok']</value>
      <webElementGuid>57284678-3c91-4097-8201-6de5ecb20e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[3]/button</value>
      <webElementGuid>ee687ce5-513f-45c3-882a-09beb8901edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'closeSmallModal-ok' and @type = 'button' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>8e270013-7689-429e-ab44-f65a03ec4c8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
