<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Go To Book Store</name>
   <tag></tag>
   <elementGuidId>8300837f-4e7e-4926-8fd8-dae33bcd5c80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gotoStore</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='gotoStore']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fd40e681-572a-4d8c-b06d-942798f142e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gotoStore</value>
      <webElementGuid>adeb4c08-75f6-4a11-9b40-5d4b9b5ef30e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>97a8e09c-1d59-4352-837a-76cebb0c56e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>23034bb1-ea9b-44d5-91ea-f1f2c97083d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go To Book Store</value>
      <webElementGuid>31f9d280-c167-4b69-bb43-90c4d2d57eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gotoStore&quot;)</value>
      <webElementGuid>9e2e5932-663f-4d93-9793-8e945d98fbbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='gotoStore']</value>
      <webElementGuid>336fc89f-e81e-424c-a7ed-e454a61808e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div[2]/div[2]/div[3]/div/button</value>
      <webElementGuid>1bb3657c-c9fc-413b-af51-8549c08698d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>25362a21-ec19-43cf-82fe-3c566291df09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'gotoStore' and @type = 'button' and (text() = 'Go To Book Store' or . = 'Go To Book Store')]</value>
      <webElementGuid>9f2baa6b-5058-4b41-a789-103abf512654</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
