<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>0ad45ee1-0eeb-4502-afcb-6512715472e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#closeSmallModal-ok</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='closeSmallModal-ok']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e2580b00-be63-40f6-be77-bb505004943f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>closeSmallModal-ok</value>
      <webElementGuid>68a3337c-5072-4cc2-a325-828962d5c3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1dab18fa-2c3b-470c-9eb7-fcea0a8dfd59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>604dd828-8d20-47c4-be1b-cfea27fddf39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>8e6f76a4-4b5d-4528-8c87-3de696a5bb28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;closeSmallModal-ok&quot;)</value>
      <webElementGuid>8fb9b1f9-1d3a-465c-9871-b8554511c664</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='closeSmallModal-ok']</value>
      <webElementGuid>7a7cca3d-5e80-4e0b-bd57-1710f2f0baa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[3]/button</value>
      <webElementGuid>adac8361-2c9c-4d58-8dd9-d9ff8a1f8361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'closeSmallModal-ok' and @type = 'button' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>3022d43d-f95e-49e7-b052-b298256acc81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
